# Generated by Django 5.0.4 on 2024-07-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_telegramuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='language',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
