# Generated by Django 5.0.4 on 2024-08-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='privilege_level',
            field=models.IntegerField(default=0),
        ),
    ]
