# Generated by Django 5.0.4 on 2024-04-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_cards_categories_users_mappings_categories_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mappings',
            old_name='status',
            new_name='mem_rating',
        ),
        migrations.AlterField(
            model_name='card',
            name='box',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=1),
        ),
    ]
