# Generated by Django 5.0.4 on 2024-04-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_categories_slug_alter_categories_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
