# Generated by Django 5.0.4 on 2024-05-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_categories_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mappings',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
