# Generated by Django 5.0.4 on 2024-05-04 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_alter_categories_slug_alter_mappings_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(max_length=255)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.testsides')),
            ],
        ),
    ]
