# Generated by Django 5.0.4 on 2024-05-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_alter_testsides_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappings',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='mappings',
            name='in_study_process',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mappings',
            name='params',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mappings',
            name='review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
