# Generated by Django 5.0.4 on 2024-05-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_remove_mappings_timestamp_mappings_in_study_process_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappings',
            name='front_side',
            field=models.BooleanField(default=False),
        ),
    ]
