# Generated by Django 5.0.4 on 2024-05-05 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_mappings_front_side'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mappings',
            old_name='front_side',
            new_name='is_back_side',
        ),
    ]
