# Generated by Django 5.0.4 on 2024-05-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_rename_front_side_mappings_is_back_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappings',
            name='upd_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
