# Generated by Django 5.0.4 on 2024-05-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_mappings_upd_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappings',
            name='upd_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
