# Generated by Django 5.0.4 on 2024-05-07 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_alter_mappings_upd_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveStudyCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_mode', models.CharField(default='new', max_length=3)),
                ('mappings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cards.mappings')),
            ],
        ),
    ]
