# Generated by Django 5.0.4 on 2024-05-07 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0015_activestudycards'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activestudycards',
            table='cards_active_study',
        ),
    ]
