# Generated by Django 5.0.4 on 2024-05-07 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0016_alter_activestudycards_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActiveStudyCards',
            new_name='ActiveStudy',
        ),
    ]
