# Generated by Django 5.0.4 on 2024-05-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0017_rename_activestudycards_activestudy'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappings',
            name='study_mode',
            field=models.CharField(default='new', max_length=3),
        ),
    ]
