# Generated by Django 5.0.4 on 2024-05-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0018_mappings_study_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappings',
            name='study_mode',
            field=models.CharField(default='new', max_length=6),
        ),
    ]
