# Generated by Django 5.0.4 on 2024-05-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0019_alter_mappings_study_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mappings',
            old_name='params',
            new_name='review_params',
        ),
        migrations.RemoveField(
            model_name='mappings',
            name='in_study_process',
        ),
        migrations.AddField(
            model_name='mappings',
            name='easiness',
            field=models.IntegerField(default='0'),
        ),
    ]
