# Generated by Django 5.0.4 on 2024-05-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0021_alter_mappings_easiness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappings',
            name='study_mode',
            field=models.CharField(default='new', max_length=10),
        ),
    ]
