# Generated by Django 5.0.4 on 2024-06-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0024_alter_categories_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
