# Generated by Django 5.0.4 on 2024-07-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0025_alter_categories_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cards',
            old_name='audio',
            new_name='audio_side1',
        ),
        migrations.AddField(
            model_name='cards',
            name='audio_side2',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
