# Generated by Django 5.0.4 on 2024-07-22 08:26

import autoslug.fields
import cards.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0027_alter_categories_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', slugify=cards.models.custom_slugify, unique=True),
        ),
    ]
