# Generated by Django 5.0.4 on 2024-08-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0028_alter_categories_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappings',
            name='has_two_sides',
            field=models.BooleanField(default=False),
        ),
    ]
