# Generated by Django 5.0.4 on 2024-08-15 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0029_mappings_has_two_sides'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappings',
            name='is_back_side',
        ),
    ]
