# Generated by Django 5.0.4 on 2024-08-17 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0030_remove_mappings_is_back_side'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cards',
            old_name='audio_side1',
            new_name='audio',
        ),
        migrations.RemoveField(
            model_name='cards',
            name='audio_side2',
        ),
    ]
