# Generated by Django 5.0.4 on 2024-08-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0031_rename_audio_side1_cards_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
